### ISSUE TITLE
Create Login and Registration Controller

### ISSUE THREAD

**Issue by shawn-mit** [Ludicrous-Ducks/AngularTake2#13]
Expected Behavior

create a controller to house the login and registration logic for a user
Actual Behavior

create a controller to house the login and registration logic for a user
Steps to Reproduce Behavior

create a controller to house the login and registration logic for a user
Module Suspected / Relevant Files

AuthCtrl.js
Related Issues

related to auth.html and AuthFactory.js

**Comment by ben-d-marks** [comment]
Redundant Issue
